name: Publish to Github Packages

on:
  push:
    branches:
      - master
    tags:
      - '**'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test using Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
        run: ./gradlew test
      - name: Assemble with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
        run: ./gradlew assemble
      - name: Publish to Registry
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}